stages:
  - check
  - deploy
  - production
checking-12-107:
  stage: check
  tags:
    - runner-107
  script:
    - 'whoami'
deploy:
  stage: deploy
  tags:
    - runner-107
  script:
    # - 'apt-get update'
    - 'pwd'
    - 'docker rm -f testweb'
    - 'docker rmi -f thanhtuyen/deploy'
    - 'docker image build -t thanhtuyen/$CI_JOB_NAME:latest .'
    # - 'docker image tag $CI_JOB_NAME:v1.$CI_JOB_ID thanhtuyen/$CI_JOB_NAME:v1.$CI_JOB_ID'
    #- 'docker image tag $CI_JOB_NAME:v1.$CI_JOB_ID thanhtuyen/$CI_JOB_NAME:latest'
production:
  stage: production
  tags:
    - runner-107
  script:
    - 'pwd'
    - 'docker run -p 80:8080 -d --name testweb thanhtuyen/deploy:latest'
 